name: OpenMod.UniTask

on:
  push:
    branches: [ main ]
    paths:
      - 'unityengine/UniTask/**'

jobs:
  build:
    name: "OpenMod.UniTask Pack"
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: ./.github/actions/nuget-pack
      id: nuget-pack
      with:
        nuspec_path: unityengine/UniTask/OpenMod.UniTask.nuspec
        nuget_key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget_push: true
