name: OpenMod.Release

on:
  create:
    tags:
      - "*"

jobs:
  gitHubRelease:
    if: github.event_name == 'create' && github.event.ref_type == 'tag'
    name: "GitHub Release"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Repository
      with:
        fetch-depth: 0
    - name: Extract version
      id: get-version
      run: echo ::set-output name=version::$(git describe --tags)
    - name: Parse version
      id: semver_parser 
      uses: booxmedialtd/ws-action-parse-semver@v1
      with:
        input_string: ${{ steps.get-version.outputs.version }}
    - name: Create release
      id: create_release
      uses: sondreb/action-release@master
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        tag: ${{ steps.get-version.outputs.version }}
        name: OpenMod Release v${{ steps.get-version.outputs.version }}
        draft: false
        prerelease: ${{ steps.semver_parser.outputs.prerelease > 0 }}