name: OpenMod.Rust.Oxide.Redist

on:
  push:
    branches: [ main ]
    paths:
      - 'rust/oxide/redist/**'

jobs:
  build:
    name: "OpenMod.Rust.Oxide.Redist Pack"
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: ./.github/actions/nuget-pack
      id: nuget-pack
      with:
        nuspec_path: rust/oxide/redist/OpenMod.Rust.Oxide.Redist.nuspec
        nuget_key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget_push: true
