name: OpenMod.Rust.Oxide.Extension

on:
  create:
    tags:
      - "*"
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/OpenMod.Rust.Oxide.Extension.yml'
      - 'rust/oxide/OpenMod.Rust.Oxide.Extension/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/OpenMod.Rust.Oxide.Extension.yml'
      - 'rust/oxide/OpenMod.Rust.Oxide.Extension/**'

jobs:
  build:
    name: "OpenMod.Rust.Oxide.Extension Build"
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2    
    - uses: ./.github/actions/project-build
      id: project-build
      with:
        project_path: rust/oxide/OpenMod.Rust.Oxide.Extension
        github_token: ${{ secrets.GITHUB_TOKEN }}
        nuget_key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget_push: true