name: OpenMod.Rust.Oxide.Redist

on:
  push:
    branches: [ main ]
    paths:
      - 'rust/oxide/redist/**'

jobs:
  build:
    name: "OpenMod.Rust.Oxide.Redist"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Repository
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - uses: nuget/setup-nuget@v1
      name: Setup NuGet
      with:
        nuget-api-key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget-version: '5.x'
    - name: Pack
      run: nuget pack rust/oxide/redist/OpenMod.Rust.Oxide.Redist.nuspec
    - name: Push to NuGet
      run: dotnet nuget push *.nupkg
             --skip-duplicate
             --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
             --source https://api.nuget.org/v3/index.json