name: OpenMod.Release

on:
  create:
    tags:
      - "*"

jobs:
  gitHubRelease:
    if: github.event_name == 'create' && github.event.ref_type == 'tag'
    name: "GitHub Release"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Repository

    # Generate semver compatible version from current tag and commit hash    
    - name: Create version
      id: get-version
      run: echo ::set-output name=version::$(git describe --tags)+$(git rev-parse --short HEAD)
      shell: bash

    - name: Check Prerelease
      id: check-prerelease
      run: "if [[ ${{ steps.get-version.outputs.version }} =~ - ]]; then
              echo ::set-output name=is_prerelease::true; 
            else 
              echo ::set-output name=is_prerelease::false; 
            fi"
      shell: bash

    - name: Create release
      id: create_release
      uses: sondreb/action-release@master
      with:
        token: ${{ secrets.RELEASE_TOKEN }}
        tag: ${{ steps.get-version.outputs.version }}
        name: OpenMod Release v${{ steps.get-version.outputs.version }}
        draft: true
        prerelease: ${{ steps.check-prerelease.outputs.is_prerelease }}