name: OpenMod.UnityEngine.Redist

on:
  push:
    branches: [ main ]
    paths:
      - 'unityengine/redist/**'

jobs:
  build:
    name: "OpenMod.UnityEngine.Redist Pack"
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: .github/actions/nuget-pack
      id: nuget-pack
      with:
        nuspec_path: unityengine/redist/OpenMod.UnityEngine.Redist.nuspec
        nuget_key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget_push: true
