name: OpenMod.Unturned.Redist

on:
  push:
    branches: [ main ]
    paths:
      - 'unturned/redist/**'

jobs:
  build:
    name: "OpenMod.Unturned.Redist Pack"
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - uses: ./.github/actions/nuget-pack
      id: nuget-pack
      with:
        nuspec_path: unturned/redist/OpenMod.Unturned.Redist.nuspecc
        nuget_key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget_push: true
