name: OpenMod.Templates

on:
  create:
    tags:
      - "*"
  push:
    branches: [ main ]
    paths:
      - 'templates/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'templates/**'

jobs:
  build:
    name: "OpenMod.Templates Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      name: Setup .NET
      with:
        dotnet-version: 5.0.100
    - name: Create version
      id: get-version
      run: echo ::set-output name=version::$(git describe --tags)+$(git rev-parse --short HEAD)
    - name: Parse version
      id: semver_parser 
      uses: booxmedialtd/ws-action-parse-semver@v1
      with:
        input_string: ${{ steps.get-version.outputs.version }}     
    - name: Update OpenMod Templates version
      run: "sed -i \"s#0.0.0#${{ steps.get-version.outputs.version }}#\" templates/OpenMod.Templates.csproj"
    - name: Update OpenMod Templates Universal version
      run: "sed -i \"s#0.0.0#${{ steps.get-version.outputs.version }}#\" templates/templates/universal/PluginTemplate.csproj"
    - name: Update OpenMod Templates Unturned version
      run: "sed -i \"s#0.0.0#${{ steps.get-version.outputs.version }}#\" templates/templates/unturned/PluginTemplate.csproj"
    - name: Build
      run: dotnet build ./templates --configuration Release

    # Push to GitHub packages on each commit        
    - name: Push to NuGet (Nightly)
      if: github.event_name == 'push'
      run: dotnet nuget push templates/bin/Release/*.nupkg
             --api-key ${{ secrets.GITHUB_TOKEN }}
             --source https://nuget.pkg.github.com/openmod/index.json
             
    # Push to NuGet on each tag, but only if the tag is not a pre-release version         
    - name: Push to NuGet (Release)
      if: github.event_name == 'create' && github.event.ref_type == 'tag' && !(steps.semver_parser.outputs.prerelease > 0)
      run: dotnet nuget push templates/bin/Release/*.nupkg
             --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
             --source https://api.nuget.org/v3/index.json
